r"""Wrapper for aphrodite_hermes.h (generated by ctypesgen)

Canonical provenance: crates/aphrodite-hermes/build.rs -> cbindgen ->
aphrodite_hermes.h -> ctypesgen -> codegen/finalize_bindings.py.
Do not modify this file.
"""
__docformat__ = "restructuredtext"

from ctypes import *  # noqa: F401, F403 - ctypesgen preamble (c_int, c_void_p, c_char_p, sizeof, ...)

# `__all__` contains the public surface: the preamble's `from ctypes import *`
# bleeds ctypes' names into this module, and without __all__ a wildcard import
# of _bindings would re-export all of them.
__all__ = ["bind_to"]

_libs = {}


# ── Runtime binder (post-processed by codegen/finalize_bindings.py) ──────────
# Importing this module NEVER loads a library (no hardcoded dylib path): the
# plugin owns the live CDLL handle (hot-reload unique-path copy) and calls
# bind_to(dylib) to replay the declarations below onto it. The loops call
# hasattr/getattr directly - no lookup adapter class is needed. errcheck is
# stripped unconditionally: pointer restypes are rewritten to c_void_p FIRST
# (a String-returning errcheck would only corrupt the raw-pointer protocol),
# and ctypesgen's CtypesPointerCast(c_void_p) casts on void* returns are safe
# to drop because c_void_p already reads the full pointer width. argtypes use
# plain c_char_p (free_string is [c_void_p] - the plugin passes it the raw
# pointer int, mirroring its _manual_ffi_setup); the String helper class is
# stripped with the dead preamble.

def bind_to(_dylib):
    """Replay the generated declarations onto an already-loaded CDLL handle.

    `_dylib` is the plugin's live handle (env override -> canonical home ->
    legacy copies -> fresh unique-path copy per generation), so the library
    path is deliberately never baked in. Pointer restypes are c_void_p
    (full-width reads - _call_json clamps to c_void_p anyway), void fns get
    None. errcheck is never applied: the plugin reads raw pointers and frees
    them through the same handle that produced them.
    """
    _libs['__APHRODITE_DYLIB__'] = _dylib
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_dispatch_tool"):
            continue
        aphrodite_hermes_dispatch_tool = getattr(_lib, "aphrodite_hermes_dispatch_tool")
        aphrodite_hermes_dispatch_tool.argtypes = [c_char_p, c_char_p]
        aphrodite_hermes_dispatch_tool.restype = c_void_p
        break

    # aphrodite_hermes.h: 21
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_list_tools"):
            continue
        aphrodite_hermes_list_tools = getattr(_lib, "aphrodite_hermes_list_tools")
        aphrodite_hermes_list_tools.argtypes = []
        aphrodite_hermes_list_tools.restype = c_void_p
        break

    # aphrodite_hermes.h: 26
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_get_schema"):
            continue
        aphrodite_hermes_get_schema = getattr(_lib, "aphrodite_hermes_get_schema")
        aphrodite_hermes_get_schema.argtypes = [c_char_p]
        aphrodite_hermes_get_schema.restype = c_void_p
        break

    # aphrodite_hermes.h: 31
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_free_string"):
            continue
        aphrodite_hermes_free_string = getattr(_lib, "aphrodite_hermes_free_string")
        aphrodite_hermes_free_string.argtypes = [c_void_p]
        aphrodite_hermes_free_string.restype = None
        break

    # aphrodite_hermes.h: 36
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_version"):
            continue
        aphrodite_hermes_version = getattr(_lib, "aphrodite_hermes_version")
        aphrodite_hermes_version.argtypes = []
        aphrodite_hermes_version.restype = c_void_p
        break

    # aphrodite_hermes.h: 51
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_call_hook"):
            continue
        aphrodite_hermes_call_hook = getattr(_lib, "aphrodite_hermes_call_hook")
        aphrodite_hermes_call_hook.argtypes = [c_char_p, c_char_p]
        aphrodite_hermes_call_hook.restype = c_void_p
        break

    # aphrodite_hermes.h: 56
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_get_schemas"):
            continue
        aphrodite_hermes_get_schemas = getattr(_lib, "aphrodite_hermes_get_schemas")
        aphrodite_hermes_get_schemas.argtypes = []
        aphrodite_hermes_get_schemas.restype = c_void_p
        break

    # aphrodite_hermes.h: 61
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_get_hooks"):
            continue
        aphrodite_hermes_get_hooks = getattr(_lib, "aphrodite_hermes_get_hooks")
        aphrodite_hermes_get_hooks.argtypes = []
        aphrodite_hermes_get_hooks.restype = c_void_p
        break

    # aphrodite_hermes.h: 66
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_proxy_health"):
            continue
        aphrodite_hermes_proxy_health = getattr(_lib, "aphrodite_hermes_proxy_health")
        aphrodite_hermes_proxy_health.argtypes = []
        aphrodite_hermes_proxy_health.restype = c_void_p
        break

    # aphrodite_hermes.h: 85
    for _lib in _libs.values():
        if not hasattr(_lib, "aphrodite_hermes_materialize_directives"):
            continue
        aphrodite_hermes_materialize_directives = getattr(_lib, "aphrodite_hermes_materialize_directives")
        aphrodite_hermes_materialize_directives.argtypes = [c_char_p]
        aphrodite_hermes_materialize_directives.restype = c_void_p
        break

    # No inserted files

    # No prefix-stripping

