#!/usr/bin/env bash
# aphrodite - download prebuilt binary from GitHub Releases
# Usage: bash download.sh [version] [target-triple]
#   version: auto-detected from BINARY_VERSION -> Cargo.toml (monorepo) ->
#            GitHub API latest release, in that order
#   target:  auto-detected from uname -sm

set -euo pipefail

# BINARY_DIR defaults to the canonical runtime home
# ($HERMES_HOME/aphrodite/binaries, falling back to ~/.hermes/aphrodite/
# binaries) - the same directory the Hermes plugin's __init__.py resolves.
# The env override keeps working exactly as before (scripts/CI may set it);
# a bare "binaries" relative default used to depend on $PWD (wherever this
# script happened to be invoked FROM), not the script's own directory,
# silently writing to the wrong place.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY_DIR="${BINARY_DIR:-${HERMES_HOME:-$HOME/.hermes}/aphrodite/binaries}"
REPO="${REPO:-PlayForm/Aphrodite}"
BIN_VERSION="${1:-}"
TARGET="${2:-}"

# ── Validate version format ──────────────────────────────────────
# Guard against a malformed BINARY_VERSION (e.g. a stray line-number
# artifact like `1|1.3.9`) producing an invalid release URL and breaking
# the update path. Enforce a strict semver-ish pattern before downloading.
VERSION_RE='^[0-9]+\.[0-9]+\.[0-9]+([-.][0-9A-Za-z.]+)?$'
validate_version() {
	local v="$1"
	case "$v" in
	'' | . | v)
		\echo "ERROR: empty/invalid BINARY_VERSION '$v'"
		return 1
		;;
	esac
	if [[ ! "$v" =~ $VERSION_RE ]]; then
		\echo "ERROR: BINARY_VERSION '$v' does not match the required pattern"
		\echo "  expected: ^[0-9]+.[0-9]+.[0-9]+([-.][0-9A-Za-z.]+)?\$"
		\echo "  (a malformed value can produce an invalid release URL and break the update path)"
		return 1
	fi
	return 0
}
if [[ -z "$BIN_VERSION" ]]; then
	# 1. BINARY_VERSION file - deployed with the plugin, always correct
	if [[ -f "$SCRIPT_DIR/BINARY_VERSION" ]]; then
		BIN_VERSION=$(head -1 "$SCRIPT_DIR/BINARY_VERSION" | tr -d '[:space:]')
	fi
fi
if [[ -z "$BIN_VERSION" ]]; then
	# 2. Cargo.toml - for developers with the full monorepo
	for f in "$SCRIPT_DIR/../../crates/aphrodite/Cargo.toml" \
		"$SCRIPT_DIR/../../crates/aphrodite-hermes/Cargo.toml" \
		"$SCRIPT_DIR/../../../crates/aphrodite/Cargo.toml"; do
		if [[ -f "$f" ]]; then
			BIN_VERSION=$(grep '^version' "$f" | head -1 | awk -F'"' '{print $2}')
			[[ -n "$BIN_VERSION" ]] && break
		fi
	done
fi
if [[ -z "$BIN_VERSION" ]]; then
	# 3. GitHub API - query latest release tag (needs network, but reliable)
	if command -v curl &>/dev/null; then
		BIN_VERSION=$(curl -fsS --connect-timeout 10 --max-time 30 "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null |
			grep '"tag_name":' | head -1 | sed 's/.*"tag_name": *"Aphrodite\/v\([^"]*\)".*/\1/')
	fi
fi
if [[ -z "$BIN_VERSION" ]]; then
	\echo "ERROR: could not determine binary version."
	\echo "  Pass explicitly: bash download.sh 1.0.5"
	\echo "  Or create a BINARY_VERSION file in $(dirname "$0")"
	exit 1
fi

# ── Guard: reject a malformed BINARY_VERSION before we build a URL from it ──
validate_version "$BIN_VERSION" || exit 1

# ── Auto-detect platform ──
if [[ -z "$TARGET" ]]; then
	ARCH=$(uname -m)
	case "$ARCH" in
	arm64 | aarch64) ARCH="aarch64" ;;
	x86_64 | amd64) ARCH="x86_64" ;;
	esac
	OS=$(uname -s | tr '[:upper:]' '[:lower:]')
	case "$OS" in
	darwin) TARGET="${ARCH}-apple-darwin" ;;
	linux) TARGET="${ARCH}-unknown-linux-gnu" ;;
	mingw* | msys* | cygwin*) TARGET="${ARCH}-pc-windows-msvc" ;;
	*)
		\echo "ERROR: unsupported OS: $OS"
		exit 1
		;;
	esac
fi

# GitHub release tags include a 'v' prefix with URL-encoded slash: Aphrodite%2Fv1.0.6
V="${BIN_VERSION#v}" # strip any existing v so we don't double it
BASE_URL="https://github.com/${REPO}/releases/download/Aphrodite%2Fv${V}"
mkdir -p "${BINARY_DIR}"

# ── SHA-256 checksum verification (mandatory in-tree sums) ────────────
# The plugin tree carries SHA256SUMS.txt GENERATED BY Build.yml (consolidated
# from the per-target release assets; committed to the child submodule by
# Publish.yml) - the pinned tree is the ONLY checksum source of truth. The
# in-tree file is MANDATORY: refuse to install when it is missing, when its
# BINARY_VERSION does not match the version being downloaded, when this
# target has no entry, or when an asset has no entry. There is NO fallback
# to release-hosted sums (catalog review, PR 118488 - a pinned tree never
# silently validates an older release or a different target).
IN_TREE_SUMS="${SCRIPT_DIR}/SHA256SUMS.txt"
if [[ ! -f "${IN_TREE_SUMS}" ]]; then
	\echo "ERROR: ${IN_TREE_SUMS} is missing - refusing to install without the in-tree checksum list"
	exit 1
fi
IN_TREE_VERSION=$(grep '^BINARY_VERSION:' "${IN_TREE_SUMS}" | head -1 | awk -F': *' '{print $2}' | tr -d '[:space:]')
if [[ -z "${IN_TREE_VERSION}" ]]; then
	\echo "ERROR: ${IN_TREE_SUMS} has no BINARY_VERSION header - refusing to install"
	exit 1
fi
if [[ "${IN_TREE_VERSION}" != "${V}" ]]; then
	\echo "ERROR: ${IN_TREE_SUMS} declares BINARY_VERSION ${IN_TREE_VERSION} but ${BIN_VERSION} is being downloaded - refusing to install (a pinned tree never silently validates an older release)"
	exit 1
fi
SUMS_FILE="$(mktemp)"
trap 'rm -f "${SUMS_FILE}"' EXIT
# Extract this target's block from the in-tree sums (keyed by the asset
# filename, which is unique across targets). A target with no block is not
# published for this BINARY_VERSION - refuse rather than skip verification.
if ! awk -v want="${TARGET}:" '$1 == want { in_block=1; next } in_block && $1 != "" && $1 !~ /:$/ { print } in_block && $1 ~ /:$/ && $1 != want { exit }' "${IN_TREE_SUMS}" 2>/dev/null | grep -q .; then
	\echo "ERROR: no checksum block for target ${TARGET} in ${IN_TREE_SUMS} - this target is not published for v${BIN_VERSION}; refusing to install"
	exit 1
fi
awk -v want="${TARGET}:" '$1 == want { in_block=1; next } in_block && $1 != "" && $1 !~ /:$/ { print } in_block && $1 ~ /:$/ && $1 != want { exit }' "${IN_TREE_SUMS}" 2>/dev/null > "${SUMS_FILE}"
\echo "  ✓ using in-tree ${IN_TREE_SUMS} (BINARY_VERSION ${IN_TREE_VERSION})"

# verify_checksum <asset-name> <dest-path>
# Checks `dest` against the SHA-256 recorded for `asset` in SUMS_FILE. The
# asset MUST have an entry and a hashing tool MUST be present - a missing
# entry or tool is a hard failure, never a skipped check (PR 118488).
verify_checksum() {
	local asset="$1" dest="$2"
	local expected actual
	# Exact match on the filename field (awk's $2), not a substring grep -
	# `shasum`'s `<hash>  <filename>` format means a substring match could
	# hit a *different*, longer asset name that happens to start with this
	# one (not a risk with today's two-line-per-target sums files, but this
	# is exact regardless).
	expected=$(awk -v want="${asset}" '$2 == want { print $1; exit }' "${SUMS_FILE}" 2>/dev/null)
	if [[ -z "$expected" ]]; then
		\echo "ERROR: ${asset} has no entry in ${IN_TREE_SUMS} - refusing to install an unverifiable asset"
		return 1
	fi
	if command -v shasum &>/dev/null; then
		actual=$(shasum -a 256 "${dest}" | awk '{print $1}')
	elif command -v sha256sum &>/dev/null; then
		actual=$(sha256sum "${dest}" | awk '{print $1}')
	else
		\echo "ERROR: no shasum/sha256sum binary found - cannot verify ${asset}; refusing to install"
		return 1
	fi
	if [[ "$expected" != "$actual" ]]; then
		\echo "ERROR: checksum mismatch for ${asset}"
		\echo "  expected: ${expected}"
		\echo "  actual:   ${actual}"
		return 1
	fi
	\echo "  ✓ ${asset} checksum verified"
}

# fetch_and_validate <asset-name> <dest-path>
# Downloads a release asset, verifies it's a real native binary
# (ELF/Mach-O/PE) and (when a sums file was found) its SHA-256 checksum,
# restoring any prior copy on failure.
fetch_and_validate() {
	local asset="$1" dest="$2" url="${BASE_URL}/$1"
	\echo "  ${asset} -> ${dest}"
	[[ -f "${dest}" ]] && mv "${dest}" "${dest}.bak" 2>/dev/null || true

	if command -v curl &>/dev/null; then
		# --connect-timeout bounds the initial handshake (fail fast on an
		# unreachable host); --max-time bounds the whole transfer generously
		# (these binaries run ~10-40MB, so this is a stall/hang guard, not a
		# realistic-bandwidth budget).
		curl -fSL --connect-timeout 10 --max-time 120 --progress-bar -o "${dest}" "${url}" || {
			\echo "ERROR: curl download failed: ${url}"
			[[ -f "${dest}.bak" ]] && mv "${dest}.bak" "${dest}"
			return 1
		}
	elif command -v wget &>/dev/null; then
		wget -q --connect-timeout=10 --timeout=120 --show-progress -O "${dest}" "${url}" || {
			\echo "ERROR: wget download failed: ${url}"
			[[ -f "${dest}.bak" ]] && mv "${dest}.bak" "${dest}"
			return 1
		}
	else
		\echo "ERROR: neither curl nor wget found"
		return 1
	fi

	local size magic valid=0
	size=$(stat -f%z "${dest}" 2>/dev/null || stat -c%s "${dest}" 2>/dev/null || echo 0)
	if [[ "$size" -eq 0 ]]; then
		\echo "ERROR: downloaded ${asset} is empty"
		[[ -f "${dest}.bak" ]] && mv "${dest}.bak" "${dest}"
		return 1
	fi
	# POSIX od one-liner (no xxd/vim dependency): -An = no addresses, -tx1 = 1-byte hex
	magic=$(head -c4 "${dest}" | od -An -tx1 | tr -d ' \n')
	case "$magic" in
	7f454c46) valid=1 ;;                                  # ELF
	cffaedfe | feedfacf | cefaedfe | cafebabe) valid=1 ;; # Mach-O
	4d5a*) valid=1 ;;                                     # PE
	esac
	if [[ "$valid" -eq 0 ]]; then
		\echo "ERROR: ${asset} has invalid magic bytes: ${magic}"
		[[ -f "${dest}.bak" ]] && mv "${dest}.bak" "${dest}"
		return 1
	fi
	if ! verify_checksum "${asset}" "${dest}"; then
		[[ -f "${dest}.bak" ]] && mv "${dest}.bak" "${dest}"
		return 1
	fi
	rm -f "${dest}.bak"
	\echo "  ✓ ${asset} (${size} bytes)"
}

# ── Asset + local names per platform ──
#   binary: the proxy executable (loaded as a subprocess)
#   dylib:  libaphrodite_hermes.* - the cdylib the Python plugin loads via ctypes
BINARY_ASSET="aphrodite-${TARGET}"
if [[ "$TARGET" == *windows* ]]; then
	BINARY_ASSET="${BINARY_ASSET}.exe"
	BINARY_PATH="${BINARY_DIR}/aphrodite.exe"
	DYLIB_ASSET="libaphrodite_hermes-${TARGET}.dll"
	DYLIB_DEST="${BINARY_DIR}/aphrodite_hermes.dll"
elif [[ "$TARGET" == *apple* ]]; then
	BINARY_PATH="${BINARY_DIR}/aphrodite"
	DYLIB_ASSET="libaphrodite_hermes-${TARGET}.dylib"
	DYLIB_DEST="${BINARY_DIR}/libaphrodite_hermes.dylib"
else
	BINARY_PATH="${BINARY_DIR}/aphrodite"
	DYLIB_ASSET="libaphrodite_hermes-${TARGET}.so"
	DYLIB_DEST="${BINARY_DIR}/libaphrodite_hermes.so"
fi

\echo "aphrodite: downloading v${BIN_VERSION} for ${TARGET} from ${BASE_URL}"
fetch_and_validate "${BINARY_ASSET}" "${BINARY_PATH}" || exit 1
chmod +x "${BINARY_PATH}"
fetch_and_validate "${DYLIB_ASSET}" "${DYLIB_DEST}" || exit 1

\echo "aphrodite v${BIN_VERSION} installed: ${BINARY_PATH} + ${DYLIB_DEST}"
