"""aphrodite _core — re-exports everything from the original _core.py split into
config, store, template, struct, and state submodules."""

# ── config.py ──────────────────────────────────────────────────
from .config import (
    _DEV,
    AUTO_EXPAND_LIMIT,
    BIN_VERSION,
    BINARY,
    BINARY_DIR,
    CATALOG_INTENT_HINTS,
    CATALOG_MODE,
    CCR_MARKER_HINT,
    CLASSIFIER_POLL,
    CODE_MULTIPLIER,
    CODE_STRUCTURE_MAP,
    CONTEXT_ENGINE,
    DEBUG_LOGGING,
    ENGINE_MIN_MSGS,
    ENGINE_PROTECT_FIRST,
    ENGINE_PROTECT_LAST,
    ENGINE_THRESHOLD_PCT,
    ENV_FILE,
    INLINE_THRESHOLD,
    MAX_REQUEST_BODY_SIZE,
    MODEL_FAMILY,
    MODEL_FAMILY_MAP,
    PLUGIN_VERSION,
    PORTS,
    PREVIEW_MAX_CHARS,
    RECURSIVE_DEPTH,
    REPO,
    RETRIEVE_GUIDANCE,
    TERMINAL_THRESHOLD,
    TOOL_THRESHOLD_CACHE,
    TOOL_THRESHOLD_TOKEN,
    _cfg_bool,
    _cfg_float,
    _cfg_int,
    _cfg_str,
    _detect_model_family,
    _load_toml_config,
    _log,
    _recent_markers,
    _set_session_model,
    _toml_section,
    reload_config,
)

# ── state.py ───────────────────────────────────────────────────
from .state import (
    _CCR_RE,
    _FILE_TOOLS,
    _conv_index,
    _get_turn_counter,
    _git_cache,
    _hash_alias,
    _increment_turn,
    _referenced_files,
    _reset_scanned_msg_idx,
    _reset_turn_counter,
    _scanned_msg_idx,
    _state,
)

# ── store.py ───────────────────────────────────────────────────
from .store import (
    _CappedStore,
    _fmt_size,
    _hash_to_trigrams,
    _index_trigrams,
    _init_trigram_index,
    _inline_bytes,
    _inline_clear,
    _inline_index,
    _inline_index_enabled,
    _inline_store,
    _inline_store_put,
    _remove_trigram_index,
)

# ── struct.py ──────────────────────────────────────────────────
from .struct import (
    _CODE_PATTERNS,
    _extract_code_structure,
)

# ── template.py ────────────────────────────────────────────────
from .template import (
    _render_marker_tmpl,
    _render_prompt_tmpl,
    _render_template,
)

# ── __all__ for strict tooling ─────────────────────────────────
__all__ = [
    "AUTO_EXPAND_LIMIT",
    "BIN_VERSION",
    "BINARY",
    "BINARY_DIR",
    "CATALOG_INTENT_HINTS",
    "CATALOG_MODE",
    "CCR_MARKER_HINT",
    "CLASSIFIER_POLL",
    "CODE_MULTIPLIER",
    "CODE_STRUCTURE_MAP",
    "CONTEXT_ENGINE",
    "DEBUG_LOGGING",
    "ENGINE_MIN_MSGS",
    "ENGINE_PROTECT_FIRST",
    "ENGINE_PROTECT_LAST",
    "ENGINE_THRESHOLD_PCT",
    "ENV_FILE",
    "INLINE_THRESHOLD",
    "MAX_REQUEST_BODY_SIZE",
    "MODEL_FAMILY",
    "MODEL_FAMILY_MAP",
    "PLUGIN_VERSION",
    "PORTS",
    "PREVIEW_MAX_CHARS",
    "RECURSIVE_DEPTH",
    "REPO",
    "RETRIEVE_GUIDANCE",
    "TERMINAL_THRESHOLD",
    "TOOL_THRESHOLD_CACHE",
    "TOOL_THRESHOLD_TOKEN",
    "_CCR_RE",
    "_CappedStore",
    "_CODE_PATTERNS",
    "_DEV",
    "_FILE_TOOLS",
    "_cfg_bool",
    "_cfg_float",
    "_cfg_int",
    "_cfg_str",
    "_conv_index",
    "_detect_model_family",
    "_extract_code_structure",
    "_fmt_size",
    "_get_turn_counter",
    "_git_cache",
    "_hash_alias",
    "_hash_to_trigrams",
    "_increment_turn",
    "_index_trigrams",
    "_init_trigram_index",
    "_inline_bytes",
    "_inline_clear",
    "_inline_index",
    "_inline_index_enabled",
    "_inline_store",
    "_inline_store_put",
    "_load_toml_config",
    "_log",
    "_recent_markers",
    "_referenced_files",
    "_remove_trigram_index",
    "_render_marker_tmpl",
    "_render_prompt_tmpl",
    "_render_template",
    "_reset_scanned_msg_idx",
    "_reset_turn_counter",
    "_scanned_msg_idx",
    "_set_session_model",
    "_state",
    "_toml_section",
    "reload_config",
]
